version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: weather_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: weatheralertservicebd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog:latest
    container_name: weather_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_app
    depends_on:
      - db
      - mailhog
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Database
      DB_HOST: db
      DB_PORT: "3306"
      DB_USER: root
      DB_PASS: password
      DB_NAME: weatheralertservicebd
      # Mail
      SMTP_HOST: mailhog
      SMTP_PORT: "1025"
      SMTP_USER: ""
      SMTP_PASS: ""
      # Gin
      GIN_MODE: release
    ports:
      - "8080:8080"
    command: ["./weather-alert-service"]

volumes:
  db_data:
